### PR TITLE
Sync develop & master

### PR DESCRIPTION
**Pull request by ovh-ux-cds**
Automerge master in develop

### CODE REVIEW

**Comment by antleblanc** [comment]
cc @marie-j

**Comment by ovh-cds** [comment]
CDS Report build-manager#2929.0 ■   
* Stage 1
  * Build dependencies and inject Sentry ■

**Comment by ovh-cds** [comment]
CDS Report build-manager#2930.0 ■   
* Stage 1
  * Build dependencies and inject Sentry ■

**Comment by antleblanc** [comment]
I close this pull request. Auto-sync will be done manually.

Thanks!

**Pull request closed without merging**
