### PR TITLE
Feat/autorenew revamp

### PR DESCRIPTION
**Pull request by marie-j**
### Related 
- [x] https://github.com/ovh-ux/ovh-module-exchange/pull/314

MANAGER-2156

cc @AxelPeter

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-manager#2296.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✘

**Comment by antleblanc** [comment]
😈
github com_ovh-ux_ovh-manager-dedicated_pull_1313

Well done!

**Comment by ovh-cds** [comment]
CDS Report build-manager#2324.0 ■   
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✔ 
  * Build manager EU ✔ 
  * Build manager US ✔ 
  * Tests ✔ 
* Stage 3
  * Prepare tar.gz for UXCI / Release ■

**Comment by ovh-cds** [comment]
CDS Report build-manager#2411.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✘

**Comment by marie-j** [comment]
Build failing because of Exchange dependency , will be fixed when release & bump will be made

**Comment by antleblanc** [comment]
@marie-j :tada: `ovh-module-exchange@9.4.7` has been released (https://github.com/ovh-ux/ovh-module-exchange/blob/master/CHANGELOG.md#947-2019-08-21)

**Pull request merged**
