### PR TITLE
Fix/contacts digest loop

### PR DESCRIPTION
**Pull request by marie-j**
### Description of the Change

When switching to tab "My services", a console error indicated that $rootscope digest as been called too many times. 
Prevent this from happening 

MBE-146

### CODE REVIEW

**Comment by FredericEspiau** [comment]
How does this prevent `$rootScope` digest not to be called too many times ?

**Comment by marie-j** [comment]
@FredericEspiau my guess is that the pagination system updates `ctrlServices.services` while loading and using a `ng-show` caused the nested `ng-repeat` to cause this error

**Comment by FredericEspiau** [comment]
Can't you convert to a datagrid then ? 😅

**Comment by marie-j** [comment]
Converting to a datagrid means a big refactor (not only refactoring but creating forms on the side and revamping controller etc). Though a Jira to address this has been created : MBE-213

**Pull request merged**
