### PR TITLE
build: remove duplicate bower dependencies

### PR DESCRIPTION
**Pull request by marie-j**
### Description of the Change

Remove @bower_components dependencies that are duplicated with yarn dependencies

### CODE REVIEW

**Comment by ovh-cds** [comment]
CDS Report build-manager#2069.0 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✘  
  * Build manager US ✘  
  * Tests ✔

**Comment by ovh-cds** [comment]
CDS Report build-manager#2069.1 ✘  
* Stage 1
  * Build dependencies and inject Sentry ✔ 
* Stage 2
  * Build manager CA ✘  
  * Build manager EU ✘  
  * Build manager US ✘  
  * Tests ✔

**Comment by frenautvh** [comment]
Are you sure everything works fine with ckeditor? I think we need to have both 2.x and 4.x versions somehow (i had to remove bower dependencies for web also, please see : https://github.com/ovh-ux/manager/blob/feat/import-web/packages/manager/apps/web/package.json)

**Comment by marie-j** [comment]
> Are you sure everything works fine with ckeditor? I think we need to have both 2.x and 4.x versions somehow (i had to remove bower dependencies for web also, please see : https://github.com/ovh-ux/manager/blob/feat/import-web/packages/manager/apps/web/package.json)

@frenautvh CKeditor is only imported once https://github.com/ovh-ux/ovh-manager-dedicated/blob/6c2ff54f241c2dae1aa2b98f80e6652a38f20e67/client/app/index.js#L80
Howevern ng-ck-editor have two versions and I've kept those

**Comment by marie-j** [comment]
> @marie-j Could you please resolve existing conflict in order to be able to merge this pull request?
> 
> Thanks!

@antleblanc Done :)

**Pull request merged**
